import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from './components/SideBar';
import SearchBar from "./components/SearchBar";
import TopBar from "./components/TopBar";
import Notes from "./components/Notes"




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      
      <body className={`${inter.className} flex   `}>
       
          <div className="flex border border-solid border-neutral-200 h-full border-b-0">
            <Sidebar className="h-full" />
          </div>
          <div className="flex-grow h-full">
            <TopBar />
            <div className="grid grid-cols-12 h-full">
            <div className="col-span-12 border border-solid border-neutral-200 border-b-0 h-full" id="children">{children}</div>
            <div className="hidden col-span-3 h-full transition-opacity duration-500 ease-in-out  " id="notes">
              <Notes />
            </div>
            </div>
          

          </div>
          
          
        
      </body>
    </html>
  );
}
